apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-demo
  labels:
    app: dotnet-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-demo
  template:
    metadata:
      labels:
        app: dotnet-demo
    spec:
      containers:
        - name: dotnet-demo
          image: {{ACRNAME}}.azurecr.io/dotnet-demo:0.0.1
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-demo-service
  labels:
    app: dotnet-demo
spec:
  selector:
    app: dotnet-demo
  ports:
    - name: http
      protocol: TCP
      port: 8443
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dotnet-demo-ingress
  labels:
    app: dotnet-demo
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/acme-challenge-type: http01
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - dotnet-demo.{{DNSZONE}}
      secretName: tls-secret
  rules:
    - host: dotnet-demo.{{DNSZONE}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dotnet-demo-service
                port:
                  name: http
